FROM node:20-slim AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

ARG WATCHTOWER_API
ARG WATCHTOWER_WEBSOCKET
ARG WATCHTOWER_PROJECT_ID
ARG MARKETPLACE_BASE_URL
ARG MARKETPLACE_AUTH_TOTP_BASE_SECRET
ARG VAPID_PUBLIC_KEY
ARG PURELYPEER_HEADER_VALUE
ARG COINGECKO_API_KEY
ARG PINATA_GATEWAY_TOKEN

ENV WATCHTOWER_API=$WATCHTOWER_API \
    WATCHTOWER_WEBSOCKET=$WATCHTOWER_WEBSOCKET \
    WATCHTOWER_PROJECT_ID=$WATCHTOWER_PROJECT_ID \
    MARKETPLACE_BASE_URL=$MARKETPLACE_BASE_URL \
    MARKETPLACE_AUTH_TOTP_BASE_SECRET=$MARKETPLACE_AUTH_TOTP_BASE_SECRET \
    VAPID_PUBLIC_KEY=$VAPID_PUBLIC_KEY \
    PURELYPEER_HEADER_VALUE=$PURELYPEER_HEADER_VALUE \
    COINGECKO_API_KEY=$COINGECKO_API_KEY \
    PINATA_GATEWAY_TOKEN=$PINATA_GATEWAY_TOKEN

RUN npx quasar build

FROM node:20-slim

WORKDIR /app

RUN npm install -g serve

COPY --from=builder /app/dist/spa /app/dist/spa

EXPOSE 8080

CMD ["serve", "-s", "/app/dist/spa", "-l", "8080"]
